/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-billing-plans': RouteRecordInfo<'admin-billing-plans', '/admin/billing-plans', Record<never, never>, Record<never, never>>,
    'admin-courses': RouteRecordInfo<'admin-courses', '/admin/courses', Record<never, never>, Record<never, never>>,
    'admin-courses-courseid-concepts': RouteRecordInfo<'admin-courses-courseid-concepts', '/admin/courses/:courseid/concepts', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-concepts-categories': RouteRecordInfo<'admin-courses-courseid-concepts-categories', '/admin/courses/:courseid/concepts/categories', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-exams': RouteRecordInfo<'admin-courses-courseid-exams', '/admin/courses/:courseid/exams', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-exams-id': RouteRecordInfo<'admin-courses-courseid-exams-id', '/admin/courses/:courseid/exams/:id', { courseid: ParamValue<true>, id: ParamValue<true> }, { courseid: ParamValue<false>, id: ParamValue<false> }>,
    'admin-courses-courseid-exams-create': RouteRecordInfo<'admin-courses-courseid-exams-create', '/admin/courses/:courseid/exams/create', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-levels': RouteRecordInfo<'admin-courses-courseid-levels', '/admin/courses/:courseid/levels', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-levels-levelid-lessons': RouteRecordInfo<'admin-courses-courseid-levels-levelid-lessons', '/admin/courses/:courseid/levels/:levelid/lessons', { courseid: ParamValue<true>, levelid: ParamValue<true> }, { courseid: ParamValue<false>, levelid: ParamValue<false> }>,
    'admin-courses-courseid-levels-levelid-lessons-lessonid-slides': RouteRecordInfo<'admin-courses-courseid-levels-levelid-lessons-lessonid-slides', '/admin/courses/:courseid/levels/:levelid/lessons/:lessonid/slides', { courseid: ParamValue<true>, levelid: ParamValue<true>, lessonid: ParamValue<true> }, { courseid: ParamValue<false>, levelid: ParamValue<false>, lessonid: ParamValue<false> }>,
    'admin-courses-courseid-questions': RouteRecordInfo<'admin-courses-courseid-questions', '/admin/courses/:courseid/questions', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-courseid-terms': RouteRecordInfo<'admin-courses-courseid-terms', '/admin/courses/:courseid/terms', { courseid: ParamValue<true> }, { courseid: ParamValue<false> }>,
    'admin-courses-categories': RouteRecordInfo<'admin-courses-categories', '/admin/courses/categories', Record<never, never>, Record<never, never>>,
    'admin-expenses': RouteRecordInfo<'admin-expenses', '/admin/expenses', Record<never, never>, Record<never, never>>,
    'admin-expenses-categories': RouteRecordInfo<'admin-expenses-categories', '/admin/expenses/categories', Record<never, never>, Record<never, never>>,
    'admin-receipts': RouteRecordInfo<'admin-receipts', '/admin/receipts', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-settings': RouteRecordInfo<'admin-settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    'admin-settings-components-general-settings': RouteRecordInfo<'admin-settings-components-general-settings', '/admin/settings/components/GeneralSettings', Record<never, never>, Record<never, never>>,
    'admin-settings-components-landing-page-settings': RouteRecordInfo<'admin-settings-components-landing-page-settings', '/admin/settings/components/LandingPageSettings', Record<never, never>, Record<never, never>>,
    'admin-trash': RouteRecordInfo<'admin-trash', '/admin/trash', Record<never, never>, Record<never, never>>,
    'admin-trophies': RouteRecordInfo<'admin-trophies', '/admin/trophies', Record<never, never>, Record<never, never>>,
    'admin-user-entitlements': RouteRecordInfo<'admin-user-entitlements', '/admin/user-entitlements', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-id': RouteRecordInfo<'admin-users-id', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'browse-courses': RouteRecordInfo<'browse-courses', '/browse-courses', Record<never, never>, Record<never, never>>,
    'checkout': RouteRecordInfo<'checkout', '/checkout', Record<never, never>, Record<never, never>>,
    'courses-id': RouteRecordInfo<'courses-id', '/courses/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'courses-select': RouteRecordInfo<'courses-select', '/courses/select', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'exam-id': RouteRecordInfo<'exam-id', '/exam/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'help-center': RouteRecordInfo<'help-center', '/help-center', Record<never, never>, Record<never, never>>,
    'help-center-article-title': RouteRecordInfo<'help-center-article-title', '/help-center/article/:title', { title: ParamValue<true> }, { title: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'payment': RouteRecordInfo<'payment', '/payment', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'revisions': RouteRecordInfo<'revisions', '/revisions', Record<never, never>, Record<never, never>>,
    'revisions-session': RouteRecordInfo<'revisions-session', '/revisions/session', Record<never, never>, Record<never, never>>,
    'revisions-summary': RouteRecordInfo<'revisions-summary', '/revisions/summary', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'study-id': RouteRecordInfo<'study-id', '/study/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
